export const pages = [
  { path: '/investors/financial-updates/', name: 'financial-updates' },
  { path: '/investors/share-price/', name: 'share-price' },
  { path: '/investors/directors/', name: 'directors' },
  { path: '/investors/directors/gary-mcgrath/', name: 'gary-mcgrath' },
  { path: '/investors/regulatory-news/', name: 'regulatory-news' },
  { path: '/markets/automotive/', name: 'automotive' },
  { path: '/legal/', name: 'legal' },
  { path: '/legal/gender-pay-gap/', name: 'gender-pay-gap' },
  { path: '/knowledge-hub/technical-literature/', name: 'technical-literature' },
  { path: '/knowledge-hub/videos/', name: 'videos' },
  { path: '/knowledge-hub/marketing-literature/', name: 'marketing-literature' },
  { path: '/knowledge-hub/statements-certificates/', name: 'statements-certificates' },
  { path: '/knowledge-hub/technical-literature/safety-information-sheets/', name: 'safety-information-sheets' },
  { path: '/zotefoams-confirms-its-commitment-to-sustainability-plastics-recycling-and-resource-management-with-recoup-membership/', name: 'recoup-membership' },
  { path: '/zotefoams-and-shincell-global-alliance/', name: 'shincell-global-alliance' },
  { path: '/zotefoams-enters-exclusivity-agreement-with-d30/', name: 'exclusivity-with-d30' },
  { path: '/foam-expo-north-america-24-26-june-2025-novi-michigan-usa-stand-1302/', name: 'foam-expo-usa-2025' },
  { path: '/pmec-india-25-27-november-2025-india-expo-centre-greater-noida-delhi-ncr-india-stand-rhc43/', name: 'pmec-india-2025' },
  { path: '/preliminary-results-unaudited-for-the-year-ended-31-december-2023/', name: 'preliminary-results-2023' },
  { path: '/performance-benefits-of-aviation-foam/', name: 'aviation-foam-benefits' },
];